import { PT_Mono } from "next/font/google";
import "./globals.css";

import Footer from "@/Components/Common/Footer";

const ptMono = PT_Mono({
	variable: "--font-pt-mono",
	subsets: ["latin"],
	weight: ["400"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<div className={`${ptMono.variable} antialiased z-10`}></div>
				<div>{children}</div>
				<div>
					<Footer />
				</div>
			</body>
		</html>
	);
}
